import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import createFixture from '../artifacts/enemy-order-tests/core.mjs';
const native=JSON.parse(fs.readFileSync(new URL('./native/enemy-birth-order-original.json',import.meta.url)));
const anm=fs.readFileSync(new URL('../local/retail/enemy.anm',import.meta.url));
function send(c,data,method){const p=c._malloc(data.length);c.HEAPU8.set(data,p);const result=c[method](p,data.length);c._free(p);return result;}
function capture(c){const p=c._enemy_order_state(),size=c._enemy_order_state_size();return JSON.parse(new TextDecoder().decode(c.HEAPU8.subarray(p,p+size)));}
function compare(c,f,name){const got=capture(c),want=f.chain;assert.equal(got.length,want.length,name+' chain');for(let i=0;i<want.length;i++){const a=got[i],b=want[i];assert.equal(a.id,b.id,name+' ID');for(let j=0;j<2;j++)assert.ok(Math.abs(a.position[j]-b.position[j])<.00004,name+' position');assert.deepEqual([a.z,a.age,a.hpImmunity,a.guard],[b.z,b.age,b.hpImmunity,+(!!(b.flags&0x20000))],name+' state');assert.deepEqual(a.privateVariables,b.privateVariables,name+' vars');assert.deepEqual(a.contexts.map(x=>[x.routine,x.time]),b.contexts.map(x=>[x.location?.routine||'',x.time]),name+' contexts');}}
async function run(r){const c=await createFixture();c._enemy_order_reset();assert.equal(send(c,Buffer.from(r.syntheticEclHex,'hex'),'_enemy_order_load'),1);assert.equal(send(c,anm,'_enemy_order_load_bank'),1);if(r.name.startsWith('background'))c._enemy_order_origin(16,-9);if(r.name.endsWith('boss-gate'))c._enemy_order_boss();for(const root of r.roots){const bytes=Buffer.from(root+'\0');send(c,bytes,'_enemy_order_spawn');}for(const f of r.frames){if(f.step==='directReentry')continue;if(f.step!=='afterBirth')c._enemy_order_pass();compare(c,f,r.name+' '+f.step);}assert.equal(c._enemy_order_unsupported(997),0);return c;}
test('typed EnemyManager matches original empty, tail/successor, nested constructors, guard and coroutine ordering',async()=>{for(const r of native.records.filter(r=>!r.name.startsWith('retail-')))await run(r);});
test('constructor native IDs migrate every existing ANM root without rebinding or aliasing another enemy',async()=>{const r=native.records.find(r=>r.name==='animated-constructor'),c=await run(r),nodes=capture(c).flatMap(e=>e.animation.map(a=>[e.id,...a]));assert.equal(nodes.length,2);assert.ok(nodes.every(a=>a[0]===a[3]));assert.notEqual(nodes[0][2],nodes[1][2]);assert.equal(new Set(nodes.map(n=>n[3])).size,2);});
test('ECL270/271 preserve world XY/camera0 offset/Z/born flags/private variables and boss guard',async()=>{for(const r of native.records.filter(r=>r.name.startsWith('background'))){const c=await run(r),rows=capture(c);for(const e of rows.filter(e=>e.z===30)){assert.deepEqual(e.position,[21,-2]);assert.equal(e.flags&0x22000000,0x22000000);assert.equal(e.animation[0][4],30);}assert.equal(c._enemy_order_unsupported(270),0);assert.equal(c._enemy_order_unsupported(271),0);}});
