import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import{spawnSync}from'node:child_process';import{pathToFileURL}from'node:url';
const root=path.resolve(import.meta.dirname,'..'),workspace=path.dirname(root),folder=path.join(root,'artifacts/font5-tests');fs.mkdirSync(folder,{recursive:true});
const python=path.join(workspace,'tools/emsdk/python/3.13.3_64bit/python.exe'),compiler=path.join(workspace,'tools/emsdk/upstream/emscripten/emcc.py');
const result=spawnSync(python,[compiler,'tests/fixtures/font5.cpp','src/game/TextGlyphs.cpp','src/game/Items.cpp','-std=c++20','-O2','-o',path.join(folder,'core.mjs'),'-sMODULARIZE=1','-sEXPORT_ES6=1','-sENVIRONMENT=node','-sEXPORTED_FUNCTIONS=["_font5_layout","_font5_glyphs","_pickup_bounds","_malloc","_free"]','-sEXPORTED_RUNTIME_METHODS=["HEAPU8","HEAPF32"]'],{cwd:root,encoding:'utf8',env:{...process.env,EM_CACHE:path.join(root,'artifacts/emscripten-cache'),EMSDK_PYTHON:python}});assert.equal(result.status,0,result.stderr||result.stdout);
const create=(await import(pathToFileURL(path.join(folder,'core.mjs')).href)).default;
test('Font5 numeric glyphs match132 actual native layout/geometry positions and scales',async()=>{
 const c=await create(),rows=JSON.parse(fs.readFileSync(path.join(root,'tests/fixtures/font5-native.json'))).rows;
 for(const row of rows){const text=new TextEncoder().encode(row.text+'\0'),ptr=c._malloc(text.length);c.HEAPU8.set(text,ptr);const n=c._font5_layout(ptr,...row.position.slice(0,2),...row.scale,...row.alignment,row.color);c._free(ptr);assert.equal(n,row.glyphs.length);const view=new DataView(c.HEAPU8.buffer),base=c._font5_glyphs();for(let i=0;i<n;i++){const at=base+i*28,g=row.glyphs[i];assert.equal(view.getInt32(at,true),g.sprite);for(let j=0;j<3;j++)assert.equal(view.getFloat32(at+4+j*4,true),g.position[j]);for(let j=0;j<2;j++)assert.equal(view.getFloat32(at+16+j*4,true),g.scale[j]);assert.equal(view.getUint32(at+24,true),g.color);}}
});
test('item pickup uses original current-frame halving and retains constructor geometry separately',async()=>{const c=await create(),rows=JSON.parse(fs.readFileSync(path.join(root,'tests/fixtures/player-item-bounds-native.json'))).rows;for(const row of rows){let p=c._pickup_bounds(row.character,1)/4;assert.deepEqual([...c.HEAPF32.slice(p,p+2)],row.currentPickupHalfExtents);assert.deepEqual([...c.HEAPF32.slice(p+2,p+4)],row.nearHalfExtents);p=c._pickup_bounds(row.character,0)/4;assert.deepEqual([...c.HEAPF32.slice(p,p+2)],row.initializedPickupDimensions);}});
