import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import createFixture from '../artifacts/laser-callback-tests/core.mjs';
const native=JSON.parse(fs.readFileSync(new URL('./native/laser-enemy-callback-original.json',import.meta.url)));
const anm=fs.readFileSync(new URL('../local/retail/bullet.anm',import.meta.url));
const close=(a,b,label)=>assert.ok(Math.abs(a-b)<.00006,`${label}: ${a} vs native ${b}`);
async function core(){const c=await createFixture();const p=c._malloc(anm.length);c.HEAPU8.set(anm,p);assert.equal(c._callback_load(p,anm.length),1);c._free(p);return c;}
function decode(kind,hex){const b=Buffer.from(hex,'hex'),f=o=>b.readFloatLE(o),i=o=>b.readInt32LE(o),h=o=>b.readInt16LE(o),p=Array(32).fill(0);[p[0],p[1],p[2]]=[f(0),f(4),f(8)];p[23]=p[24]=-1;if(kind===0){[p[3],p[5],p[4],p[6],p[7],p[8],p[13],p[18],p[20],p[21],p[23],p[24]]=[f(12),f(16),f(20),f(24),f(28),f(32),f(40),i(44),h(36),h(38),i(0x1e0),i(0x1e4)];}if(kind===1){[p[9],p[10],p[11],p[3],p[12],p[5],p[4],p[7],p[8],p[14],p[15],p[16],p[17],p[22],p[13],p[20],p[21],p[18],p[23],p[24]]=[f(12),f(16),f(20),f(24),f(28),f(32),f(36),f(40),f(44),i(48),i(52),i(56),i(60),i(72),f(76),h(80),h(82),i(84),i(64),i(68)];}if(kind===2){[p[3],p[7],p[8],p[20],p[21],p[19],p[13],p[18],p[23],p[24]]=[f(12),f(16),f(20),h(24),h(26),i(28),f(32),i(36),i(0x1d8),i(0x1dc)];}return p;}
function run(c,r){c._callback_reset();for(const l of r.input.lasers){c.HEAPF32.set(decode(l.kind,l.profileHex),c._callback_input()/4);c._callback_add_laser(l.kind,...l.position,...l.initial,l.angle,l.length,l.speed,l.age,l.phase);}for(const b of r.input.bullets)c._callback_add_bullet(+b.vmAlive,b.phase,b.marker,...b.position,b.sourceAngle,b.sourceSpeed,...b.initialPosition);c._callback_rng(...r.rngBefore);c._callback_run(r.input.selector,r.input.integers[0],r.input.floats[0],r.input.floats[1]);}
function compareShooter(c,p,e,label){const a=[...c.HEAPF32.slice(p/4,p/4+124)];for(let i=0;i<2;i++)close(a[i],e.position[i],label+' pos'+i);for(const[i,k]of [[3,'angle'],[4,'spacing'],[5,'speed'],[6,'slow']])close(a[i],e[k],label+' '+k);assert.deepEqual(a.slice(7,16),['type','color','count','layers','mode','flags','fireSound','transformSound','first'].map(k=>e[k]),label+' types');for(let i=0;i<18;i++){const p=16+i*6,r=e.records[i];close(a[p],r.a,label+' r'+i+' a');close(a[p+1],r.b,label+' r'+i+' b');assert.deepEqual(a.slice(p+2,p+6),[r.c,r.d,r.kind,r.concurrent],label+' r'+i);}}
test('original callbacks3/4/5 zero, one and multiple objects match exact emitted records and final Shooters',async()=>{const c=await core();let n=0;for(const r of native.records){run(c,r);assert.equal(c._callback_emissions(),r.emissions.length,r.input.name);for(let i=0;i<r.emissions.length;i++){compareShooter(c,c._callback_emission(i),r.emissions[i],r.input.name+' '+i);n++;}if(r.shooter)compareShooter(c,c._callback_shooter(r.input.selector),r.shooter,r.input.name+' final');assert.equal(c._callback_unknown(),0,r.input.name);}assert.equal(n,58);});
test('callback clears and fresh type0 laser geometry match original list order and creation fields',async()=>{const c=await core();for(const r of native.records){run(c,r);const p=c._callback_lasers()/4;assert.equal(c.HEAPF32[p],r.lasers.length,r.input.name);for(let i=0;i<r.lasers.length;i++){const a=[...c.HEAPF32.slice(p+1+i*16,p+17+i*16)],b=r.lasers[i];assert.deepEqual(a.slice(0,3),[b.kind,b.serial,b.phase],r.input.name+' identity');for(let j=0;j<3;j++){close(a[3+j],b.position[j],r.input.name+' position');close(a[6+j],b.initialPosition[j],r.input.name+' initial');}for(let j=0;j<4;j++)close(a[9+j],b.angleLengthWidthSpeed[j],r.input.name+' geometry');assert.equal(a[13],b.protection);} }});
test('two callback RNG values per emission and real cancel ANM child RNG match original interleaving',async()=>{const c=await core();for(const r of native.records){run(c,r);assert.deepEqual([c._callback_seed(),c._callback_calls()],r.rngAfter,r.input.name+' final RNG');const got=Array.from({length:c._callback_events()},(_,i)=>Array.from({length:4},(_,j)=>c._callback_event(i,j))).filter(e=>e[0]===0||e[0]===1);const want=r.events.filter(e=>e.kind==='rng32'||e.kind==='emit');assert.equal(got.length,want.length,r.input.name+' RNG/event count');for(let i=0;i<want.length;i++){const a=got[i],b=want[i];assert.deepEqual(b.kind==='rng32'?a.slice(0,3):a,[b.kind==='rng32'?0:1,...(b.kind==='rng32'?b.rng:[b.index,...b.rng])],r.input.name+' event '+i);}}});
test('invalid spacing and native unsafe full-pool requests are observable without a hang or memory write',async()=>{const c=await core(),r=native.records.find(r=>r.input.name==='5-one-kind0');run(c,{...r,input:{...r.input,floats:[0,2,0,0]}});assert.equal(c._callback_unknown(),1);assert.equal(c._callback_emissions(),0);c._callback_reset();c.HEAPF32.set(decode(0,r.input.lasers[0].profileHex),c._callback_input()/4);for(let i=0;i<256;i++)c._callback_add_laser(0,0,100,0,0,100,0,0,128,2,0,2);c._callback_add_bullet(1,1,1,0,100,0,0,2,0,100,0);c._callback_run(4,0,0,0);assert.equal(c._callback_unknown(),1);assert.equal(c.HEAPF32[c._callback_lasers()/4],256);});
function compareTarget(c,s,label){const a=[...c.HEAPF32.slice(c._target_state()/4,c._target_state()/4+14)];for(const[i,k]of [[0,s.position[0]],[1,s.position[1]],[2,s.velocity[0]],[3,s.velocity[1]],[4,s.speed],[5,s.angle],[8,s.elapsed[2]],[10,s.interpolation[2]],[11,s.target[0]],[12,s.target[1]]])close(a[i],k,label+' '+i);assert.deepEqual([a[6],a[7],a[9],a[13]],[s.active,s.elapsed[1],s.interpolation[1],0],label+' active/clocks');}
test('position extension2000000 matches 1058 original callbacks including 180-tick movement, relative coordinates, all scalar curves and fractional game rates',async()=>{const c=await core(),source=JSON.parse(fs.readFileSync(new URL('./native/bullet-target-motion-original.json',import.meta.url)));let n=0;for(const r of source.records){const b=r.initial,q=r.record;assert.equal(c._target_begin(...b.position,b.angle,b.speed,q.a,q.b,q.c,q.d),1);compareTarget(c,r.frames[0],JSON.stringify(q)+' initial');for(const f of r.frames.slice(1)){assert.equal(c._target_tick(r.gameRate,0),f.returnValue,JSON.stringify(q)+' return '+f.frame);compareTarget(c,f.beforeIntegration,JSON.stringify(q)+' before '+f.frame);c._target_integrate(r.gameRate);compareTarget(c,f,JSON.stringify(q)+' after '+f.frame);n++;}}assert.equal(n,1058);});
test('unrecovered special vector interpolation is counted explicitly at extension start',async()=>{const c=await core();for(const mode of [7,8,17,255]){assert.equal(c._target_begin(0,120,0,2,50,100,180,mode),0);const p=c._target_state()/4;assert.equal(c.HEAPF32[p+13],1);assert.equal(c.HEAPF32[p+6],0);}});
test('Enemy owner migration preserves live root/child IDs, VM clocks and shared RNG; rejects live key conflicts and supports normal cleanup',async()=>{const c=await core();assert.equal(c._callback_owner_migration(),1);});
