import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {AnimationSampler} from '../src/animation.mjs';import {StageBackground,primitiveSize} from '../src/stage-background.mjs';
import {quadCorners,readCoreHud,fragmentInterrupt,groupedNumber,hudGlyphs,readCoreAnimationPoses,animationBankName,readCoreMessage,decodeMessageHex,messageTextPoses,dialogueMetrics} from '../src/renderer.mjs';
import {easing} from '../src/easing.mjs';
const atlases=JSON.parse(fs.readFileSync(new URL('../site/assets/atlases.json',import.meta.url)));
const background=JSON.parse(fs.readFileSync(new URL('../site/assets/stage01-background.json',import.meta.url)));
const original=JSON.parse(fs.readFileSync(new URL('fixtures/presentation-original.json',import.meta.url)));
test('TH12 easing distinguishes fourth-power acceleration, quadratic deceleration and smooth curves',()=>{assert.equal(easing(.5,3),.0625);assert.equal(easing(.5,4),.75);assert.equal(easing(.25,9),.125);assert.equal(easing(.75,9),.875);assert.equal(easing(.25,12),.375);assert.equal(easing(.5,15),0);assert.equal(easing(.5,16),1);});
test('enemy ANM stop holds the last pose instead of repeatedly restarting the sprite list',()=>{const a=new AnimationSampler(atlases);assert.equal(a.sample('stgenm01',1,20).sprite,7);assert.equal(a.sample('stgenm01',1,400).sprite,7);assert.equal(a.sample('stgenm01',1,450).sprite,7);});
test('retail player shot script retains color, rotation and scale',()=>{const a=new AnimationSampler(atlases),s=a.sample('pl02',5,0);assert.equal(s.sprite,24);assert.ok(Math.abs(s.sx-1.4)<1e-6);assert.ok(Math.abs(s.rotation-Math.PI/4)<1e-6);assert.equal(s.g,128/255);assert.equal(a.sample('pl02',5,24).sprite,24);});
test('bullet colors use retail launch table and normal-launch interrupt',()=>{const a=new AnimationSampler(atlases),type=atlases.bullet.types[2],s=a.sample('bullet',type.script,0,type.colors[0]);assert.equal(s.sprite,16);assert.equal(s.alpha,1);assert.equal(s.sx,1);assert.equal(s.rotate,true);assert.equal(a.sample('bullet',type.script,80,type.colors[3]).sprite,19);});
test('STD camera matches 14 original instruction samples, including first-tick advancement and byte fog',()=>{const b=new StageBackground(background,atlases);for(const n of original.camera){const s=b.sample(n.frame);for(const key of ['position','direction','up'])s[key].forEach((v,i)=>assert.ok(Math.abs(v-n[key][i])<1e-4,`${key} at ${n.frame}`));assert.equal(s.fov,n.fov);assert.deepEqual(s.fog.slice(3),n.fogRange);assert.deepEqual(s.fog.slice(0,3).map(n=>Math.round(n*255)),[16,8,0].map(shift=>(Number(n.fogArgb)>>>shift)&255));}});
test('stage01 projection remains finite through camera loops and both native clipping planes',()=>{const b=new StageBackground(background,atlases);for(const frame of [0,1,300,600,690,1202,1746,5042,10000]){const g=b.geometry(frame);assert.ok(g.triangles.length>0);for(const t of g.triangles)for(const v of t.vertices){assert.ok([v.x,v.y,v.depth,v.fog].every(Number.isFinite));assert.ok(v.depth>=30-1e-8&&v.depth<=1800+1e-8);assert.ok(v.fog>=0&&v.fog<=1);}}});
function fixtureCommands(instructions){let offset=0;return [...instructions.map(c=>{const raw=Buffer.alloc(c.values.length*4);[...c.formats].forEach((format,i)=>format==='f'?raw.writeFloatLE(c.values[i],i*4):raw.writeInt32LE(c.values[i],i*4));const command={offset,op:c.op,time:0,mask:0,ints:c.values.map((_,i)=>raw.readInt32LE(i*4)),floats:c.values.map((_,i)=>raw.readFloatLE(i*4))};offset+=8+raw.length;return command;}),{offset,op:63,time:0,mask:0,ints:[],floats:[]}];}
test('ANM transform, flags, color and interpolation match 28 original interpreter ticks',()=>{for(const record of original.anm){const initialize=[{op:76,formats:'iii',values:[255,255,255]},{op:77,formats:'i',values:[255]}];const a=new AnimationSampler({fixture:{scripts:{0:{commands:fixtureCommands([...initialize,...record.instructions])}}}});for(const n of record.frames){const s=a.sample('fixture',0,n.tick);for(const [keys,values]of [[['x','y','z'],n.position],[['rx','ry','rotation'],n.rotation],[['sx','sy'],n.scale],[['u','v'],n.uv]])keys.forEach((key,i)=>assert.ok(Math.abs(s[key]-values[i])<1e-6,`${record.name}:${n.tick}:${key}`));const rgba=(r,g,b,a)=>((Math.round(a*255)<<24)|(Math.round(r*255)<<16)|(Math.round(g*255)<<8)|Math.round(b*255))>>>0;assert.equal(rgba(s.useColor2?s.r2:s.r,s.useColor2?s.g2:s.g,s.useColor2?s.b2:s.b,s.useColor2?s.alpha2:s.alpha),Number(s.useColor2?n.secondary:n.primary));assert.equal(rgba(s.r2,s.g2,s.b2,s.alpha2),Number(n.secondary));if(record.name==='transform_uv_flags'){assert.equal(s.anchorX,1);assert.equal(s.anchorY,1);assert.equal(s.mode,1);assert.equal(s.blend,1);assert.equal(s.point,true);}}}});
test('STD nonzero dimensions override ANM scale, including the cloud script scale 2',()=>{const a=new AnimationSampler(atlases).sample('stage01',4,0),s=atlases.stage01.sprites[a.sprite];assert.deepEqual([a.sx,a.sy],[2,2]);assert.deepEqual(primitiveSize(background.objects[1].quads[0],a,s),[1024,512]);assert.deepEqual(primitiveSize({size:[0,0]},a,s),[s.w*2,s.h*2]);});
test('retail HUD frame expands all eleven children with original top-left anchors',()=>{const a=new AnimationSampler(atlases),s=a.sampleAll('front',0,100);assert.equal(s.filter(s=>s.sprite!==null).length,11);const right=s.find(s=>s.script===3);assert.equal(right.x,416);assert.equal(right.y,0);assert.equal(right.anchorX,1);assert.equal(right.anchorY,1);assert.deepEqual(quadCorners(416,0,224,480,0,1,1),[[416,0],[640,0],[640,480],[416,480]]);});
test('HUD native counters select original fragment interrupts and original numeric glyphs',()=>{assert.equal(fragmentInterrupt(0,2,3),2);assert.equal(fragmentInterrupt(2,2,3),10);assert.equal(fragmentInterrupt(3,2,3),3);assert.equal(fragmentInterrupt(2,2,0),7);assert.equal(groupedNumber(123456780),'123,456,780');const glyphs=hudGlyphs('123,456,780',620,72,1,true);assert.equal(glyphs[0].id,244);assert.equal(glyphs[0].x,504);assert.equal(glyphs[3].id,257);assert.equal(glyphs[3].y,75);assert.equal(glyphs.at(-1).x,608);const frac=hudGlyphs('43',560,159,.6);assert.equal(frac[0].id,247);assert.equal(frac[1].x,567.2);});
test('HUD ABI supports extended state and the earlier 20-field core',()=>{const HEAPU8=new Uint8Array(1024),core={HEAPU8,_th12_hud:()=>0};assert.equal(readCoreHud(core).length,20);core._th12_hud_size=()=>41;const h=readCoreHud(core);assert.equal(h.length,41);h[40]=123;assert.equal(new Float32Array(HEAPU8.buffer)[40],123);core._th12_hud_size=()=>400;assert.throws(()=>readCoreHud(core),/状态记录/);});
test('logical ANM pose ABI reads authoritative colors and resolved coordinates without sampling',()=>{
  const HEAPU8=new Uint8Array(256),view=new DataView(HEAPU8.buffer),F=(i,n)=>view.setFloat32(i*4,n,true),U=(i,n)=>view.setUint32(i*4,n,true);
  F(0,112.25);F(1,206.5);F(5,.25);F(6,2);F(7,3);U(14,0x80102030);U(15,0x40223344);U(16,2);U(17,7);U(18,11);U(19,1);U(20,1);U(21,2);U(22,1);U(24,1);U(25,2);U(26,19);U(27,42);F(28,.75);
  const core={HEAPU8,_th12_anm_draw:()=>1,_th12_anm_draw_ptr:()=>0,_th12_anm_draw_stride:()=>128},[p]=readCoreAnimationPoses(core,3);
  assert.deepEqual([p.x,p.y,p.a.x,p.a.y],[112.25,206.5,0,0]);assert.deepEqual([p.a.name,p.a.sprite,p.a.layer,p.a.rotate,p.owner,p.id],['stgenm03',7,11,true,42,19]);assert.equal(p.a.alpha,128/255);assert.equal(p.a.r,16/255);assert.equal(p.a.point,true);assert.equal(p.alpha,.75);
  U(24,0x10001);assert.equal(readCoreAnimationPoses(core,3)[0].a.r,34/255);assert.deepEqual(readCoreAnimationPoses({}),[]);core._th12_anm_draw_stride=()=>36;assert.throws(()=>readCoreAnimationPoses(core),/姿态/);assert.equal(animationBankName(8,7),'text');assert.equal(animationBankName(3,5),'stgenm05m');
});
test('dialogue snapshots decode the original CP932 bytes and reject invalid lengths',()=>{
  assert.equal(decodeMessageHex('826c827220835383568362834e'),'ＭＳ ゴシック');assert.throws(()=>decodeMessageHex('xx'),/字符/);
  const bytes=new TextEncoder().encode(JSON.stringify({active:true,textHex:['82a082a2','']})),HEAPU8=new Uint8Array(1024);HEAPU8.set(bytes,4);
  const core={HEAPU8,_th12_message:()=>4,_th12_message_size:()=>bytes.length};assert.equal(readCoreMessage(core).textHex[0],'82a082a2');core._th12_message_size=()=>2000;assert.throws(()=>readCoreMessage(core),/状态/);assert.equal(readCoreMessage({}),null);
});
test('dialogue draws the four native text rectangles using logical visibility and scale',()=>{
  const samples=JSON.parse(fs.readFileSync(new URL('fixtures/anm-retail-original.json',import.meta.url))),text=samples.records.filter(r=>r.name==='text'),message={active:true,textRecords:[0,1,2,3].map(style=>({textHex:'82a082a2',offset:0,spacing:0,style:style%3,color:0xf8f08f}))};
  assert.equal(text.length,4);for(const record of text)for(const frame of record.frames){const pose={a:{name:'text',sprite:record.script,visible:frame.visible,alpha:(frame.primary>>>24)/255,sx:frame.scale[0],sy:frame.scale[1],anchorX:1,anchorY:1},x:frame.position[0]+8,y:frame.position[1],alpha:1},views=messageTextPoses(message,[pose],atlases);assert.equal(views.length,frame.visible?1:0);if(views.length){assert.equal(views[0].text,'あい');assert.deepEqual(views[0].metrics,{width:354,height:17,sourceWidth:730,sourceHeight:36});assert.equal(views[0].a.sy,frame.scale[1]);assert.equal(views[0].x,56);}}
  assert.equal(animationBankName(11),'ascii');assert.deepEqual(dialogueMetrics(512,17),{width:512,height:17,sourceWidth:1024,sourceHeight:36});
});
test('animation seeking is invariant and released entity tracks do not retain a frame history',()=>{const a=new AnimationSampler(atlases),early=a.sampleAll('front',0,3);a.sampleAll('front',0,3000);assert.deepEqual(a.sampleAll('front',0,3),early);for(const track of a.tracks.values())assert.equal(track.frames.length,1);a.beginFrame();a.sample('pl02',0,60,null,{entityId:1});a.endFrame();assert.equal(a.tracks.size,1);a.beginFrame();a.sample('pl02',0,61,null,{entityId:2});a.endFrame();assert.equal(a.tracks.size,1);});
test('UFO HUD position/color interrupts resume the original holding script',()=>{const a=new AnimationSampler(atlases);for(let i=0;i<3;i++){const s=a.sample('front',80,40,null,{interrupts:[7+i,10+i,2]});assert.equal(s.x,52+21*i);assert.equal(s.y,456);assert.equal(s.sprite,59+i);assert.equal(s.alpha,1);}});
