"""Export TH12's hostile bullet tables and execute its actual color callback.

The table is data required by the logical ANM sprite remap, not rendering code.
Only 40d430 executes; no GPU, game startup, or full replay oracle is claimed.
"""
import pathlib,sys,struct,json
ROOT=pathlib.Path(__file__).resolve().parents[2];sys.path.insert(0,str(ROOT.parent/'tools/python'))
import pefile,capstone
from unicorn import Uc,UC_ARCH_X86,UC_MODE_32
from unicorn.x86_const import UC_X86_REG_ECX,UC_X86_REG_EDX,UC_X86_REG_EAX,UC_X86_REG_ESP,UC_X86_REG_EIP
from native_anm_resource import check_original,EXE_SHA256
exe=ROOT.parent/'th12/th12.exe';check_original(exe);pe=pefile.PE(str(exe))
raw=pe.get_data(0x4af280-pe.OPTIONAL_HEADER.ImageBase,31*0xd0)
vm=Uc(UC_ARCH_X86,UC_MODE_32);vm.mem_map(0x400000,(pe.OPTIONAL_HEADER.SizeOfImage+4095)&~4095);vm.mem_write(0x400000,pe.get_memory_mapped_image())
vm.mem_map(0x1000000,0x10000);vm.mem_map(0x2000000,0x10000)
obj,bullet,stack,stop=0x2000000,0x2001000,0x100e000,0x100f000
put=lambda at,fmt,*values:vm.mem_write(at,struct.pack('<'+fmt,*values))
put(obj+0x4b0,'I',bullet);records=[]
for kind in range(31):
    row=raw[kind*0xd0:(kind+1)*0xd0];colors=[];put(bullet+0x9f4,'h',kind)
    for color in range(16):
        put(bullet+0x9f6,'h',color);selected=[]
        for sprite in range(3):
            put(stack,'I',stop);vm.reg_write(UC_X86_REG_ESP,stack);vm.reg_write(UC_X86_REG_ECX,obj);vm.reg_write(UC_X86_REG_EDX,sprite)
            vm.emu_start(0x40d430,stop,count=100)
            if vm.reg_read(UC_X86_REG_EIP)!=stop:raise RuntimeError('Native sprite callback budget')
            selected.append(struct.unpack('<i',struct.pack('<I',vm.reg_read(UC_X86_REG_EAX)))[0])
        colors.append(selected)
    table_colors=[list(struct.unpack_from('<iii',row,4+color*12)) for color in range(16)]
    expected=[[0,1,2] for _ in range(16)] if table_colors[0][0]<0 else table_colors
    if colors!=expected:raise ValueError(f'Native table interpretation differs for bullet {kind}')
    records.append({'type':kind,'script':struct.unpack_from('<i',row)[0],
        'hitbox':struct.unpack_from('<f',row,0xc4)[0],'group':struct.unpack_from('<i',row,0xc8)[0],
        'cancelEffectClass':struct.unpack_from('<i',row,0xcc)[0],'remap':table_colors[0][0]>=0,
        'tableColors':table_colors,'nativeColors':colors})
out=ROOT/'tests/fixtures/bullet-visual-original.json';out.write_text(json.dumps({
    'schema':'th12-original-bullet-color-samples/1','originalExeSha256':EXE_SHA256,
    'provider':'Original 40d430 callback executed for 31 types x 16 colors x 3 ANM sprite roles; table4af280 strideD0',
    'wholeGameDeterminism':False,'wholePresentationOracle':False,'gpuExecuted':False,'records':records},indent=2)+'\n',encoding='utf-8')
header=['// Numeric retail table 0x4af280, stride 0xd0; native callback 0x40d430.',
    '// Generated by scripts/reverse/sample-bullet-visuals.py after checking the',
    '// pinned TH12 1.00b executable. ANM roles: 0 body, 1 spawn, 2 cancel.',
    '#pragma once','#include <array>','namespace th12::bullet_visuals {',
    'struct Appearance {int script;float hitbox;int group,cancelEffectClass;bool remap;std::array<std::array<int,3>,16> colors;};',
    'inline constexpr std::array<Appearance,31> appearances={{']
for row in records:
    colors=','.join('{{'+','.join(map(str,c))+'}}' for c in row['tableColors'])
    header.append(' {'+str(row['script'])+','+format(row['hitbox'],'.9g')+'.f,'+str(row['group'])+','+str(row['cancelEffectClass'])+','+str(row['remap']).lower()+',{{'+colors+'}}},')
header.extend(['}};',
    '// Native identity types bypass lookup for every sprite ID. The ordinary',
    '// remapped scripts use only roles 0..2; reject invalid table coordinates',
    '// instead of reading beyond the resource table.',
    'inline bool resolve(int type,int color,int sprite,int& result){',
    ' if(type<0||type>=31)return false;const auto& row=appearances[type];',
    ' if(!row.remap){result=sprite;return true;}',
    ' if(color<0||color>=16||sprite<0||sprite>=3)return false;',
    ' result=row.colors[color][sprite];return true;',
    '}',
    '} // namespace th12::bullet_visuals'])
(ROOT/'src/bullet_visuals.hpp').write_text('\n'.join(header)+'\n',encoding='utf-8')
cs=capstone.Cs(capstone.CS_ARCH_X86,capstone.CS_MODE_32)
asm='\n'.join(f'{i.address:08x} {i.mnemonic:9} {i.op_str}' for i in cs.disasm(pe.get_data(0xd430,0x3b),0x40d430))
(ROOT/'artifacts/reverse/bullet-sprite-remap.asm').write_text(asm+'\n',encoding='utf-8')
print(f'{out}: 1488 actual callback samples; src/bullet_visuals.hpp generated')
